name: build
on: [push, workflow_dispatch]:
    branches: 
      - master
    paths:
     - "**/*.go"
     - "go.mod"
     - "go.sum"
     - ".github/workflows/*.yml"
  create:
    tags:
      - "v*"

env:
  GO111MODULE: on

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set tag name
        run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      - name: Build
        run: |
          go mod tidy
          go build -o btsniffer -trimpath -ldflags "-s -w -buildid="
          zip btsniffer-linux.zip btsniffer

      - name: Release binaries
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$CURRENT_TAG" -t "ATTENTION" -n "$CURRENT_TAG is released. (CAUTIOUS: use at your own risk)" *.zip
